[2024-01-12T20:51:30.679+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fdic_ncua_staging.create_staging_ncua_fs220_temp manual__2024-01-12T20:51:29.189854+00:00 [queued]>
[2024-01-12T20:51:30.692+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fdic_ncua_staging.create_staging_ncua_fs220_temp manual__2024-01-12T20:51:29.189854+00:00 [queued]>
[2024-01-12T20:51:30.693+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T20:51:30.701+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): create_staging_ncua_fs220_temp> on 2024-01-12 20:51:29.189854+00:00
[2024-01-12T20:51:30.705+0000] {standard_task_runner.py:60} INFO - Started process 9607 to run task
[2024-01-12T20:51:30.710+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fdic_ncua_staging', 'create_staging_ncua_fs220_temp', 'manual__2024-01-12T20:51:29.189854+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-staging.py', '--cfg-path', '/tmp/tmp190o55z7']
[2024-01-12T20:51:30.712+0000] {standard_task_runner.py:88} INFO - Job 104: Subtask create_staging_ncua_fs220_temp
[2024-01-12T20:51:30.767+0000] {task_command.py:423} INFO - Running <TaskInstance: fdic_ncua_staging.create_staging_ncua_fs220_temp manual__2024-01-12T20:51:29.189854+00:00 [running]> on host c111cf247bc6
[2024-01-12T20:51:30.798+0000] {abstractoperator.py:708} ERROR - Exception rendering Jinja template for task 'create_staging_ncua_fs220_temp', field 'sql'. Template: 'sql/temp/create_staging_ncua_fs220_temp.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/temp/create_staging_ncua_fs220_temp.sql
[2024-01-12T20:51:30.799+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2335, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2466, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2878, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1248, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 700, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 171, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/temp/create_staging_ncua_fs220_temp.sql
[2024-01-12T20:51:30.806+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fdic_ncua_staging, task_id=create_staging_ncua_fs220_temp, execution_date=20240112T205129, start_date=20240112T205130, end_date=20240112T205130
[2024-01-12T20:51:30.814+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 104 for task create_staging_ncua_fs220_temp (sql/temp/create_staging_ncua_fs220_temp.sql; 9607)
[2024-01-12T20:51:30.845+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T20:51:30.866+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
