[2024-01-12T21:14:55.958+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fdic_ncua_staging.staging_fdic_institutions.check_for_duplicates manual__2024-01-12T21:14:53.177878+00:00 [queued]>
[2024-01-12T21:14:55.963+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fdic_ncua_staging.staging_fdic_institutions.check_for_duplicates manual__2024-01-12T21:14:53.177878+00:00 [queued]>
[2024-01-12T21:14:55.963+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T21:14:55.970+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): staging_fdic_institutions.check_for_duplicates> on 2024-01-12 21:14:53.177878+00:00
[2024-01-12T21:14:55.975+0000] {standard_task_runner.py:60} INFO - Started process 10034 to run task
[2024-01-12T21:14:55.977+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fdic_ncua_staging', 'staging_fdic_institutions.check_for_duplicates', 'manual__2024-01-12T21:14:53.177878+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-staging.py', '--cfg-path', '/tmp/tmpu0rem1gc']
[2024-01-12T21:14:55.978+0000] {standard_task_runner.py:88} INFO - Job 138: Subtask staging_fdic_institutions.check_for_duplicates
[2024-01-12T21:14:56.005+0000] {task_command.py:423} INFO - Running <TaskInstance: fdic_ncua_staging.staging_fdic_institutions.check_for_duplicates manual__2024-01-12T21:14:53.177878+00:00 [running]> on host c111cf247bc6
[2024-01-12T21:14:56.044+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fdic_ncua_staging' AIRFLOW_CTX_TASK_ID='staging_fdic_institutions.check_for_duplicates' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T21:14:53.177878+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T21:14:53.177878+00:00'
[2024-01-12T21:14:56.050+0000] {base.py:83} INFO - Using connection ID 'alpharank_de_eval' for task execution.
[2024-01-12T21:14:56.461+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fdic-ncua-staging.py", line 33, in check_for_duplicates
    cur.execute(dupe_sql)
psycopg2.errors.UndefinedTable: relation "staging.fdic_institutions_temp" does not exist
LINE 5:                 FROM staging.fdic_institutions_temp
                             ^

[2024-01-12T21:14:56.471+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=fdic_ncua_staging, task_id=staging_fdic_institutions.check_for_duplicates, execution_date=20240112T211453, start_date=20240112T211455, end_date=20240112T211456
[2024-01-12T21:14:56.480+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 138 for task staging_fdic_institutions.check_for_duplicates (relation "staging.fdic_institutions_temp" does not exist
LINE 5:                 FROM staging.fdic_institutions_temp
                             ^
; 10034)
[2024-01-12T21:14:56.485+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T21:14:56.502+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
